spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
DATASOURCE: "{\"username\":\"postgres\",\"password\":\"gmo123\",\"engine\":\"postgresql\",\"host\":\"10.1.10.252\",\"port\":5432,\"dbname\":\"avivadb\"}"


---

spring:
  application:
    name: user-service
  profiles:
    active: prod
  datasource:
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
DATASOURCE: "{\"username\":\"postgres\",\"password\":\"gmo123\",\"engine\":\"postgresql\",\"host\":\"10.1.10.252\",\"port\":5432,\"dbname\":\"avivadb1\"}"

